### PR TITLE
Allow enabling and disabling of certain CPE features

### LINKED ISSUE #639: Allow disabling of certain CPE features.
For instance some people might want the CustomBlocks extension to be disabled, but keep most of the other CPE features enabled like the env features.

### PR DESCRIPTION
**Pull request by forkiesassds**
Closes #639.

### CODE REVIEW

**Comment by UnknownShadow200** [comment]
Extensions must be an instance field, you cannot make it a static field like that - otherwise every player would share the same CPE extension support state

**Comment by forkiesassds** [comment]
> 
> 
> Extensions must be an instance field, you cannot make it a static field like that - otherwise every player would share the same CPE extension support state

I've now made it non-static.

**Comment by UnknownShadow200** [comment]
How many CPE extensions are you anticipating to disable?

**Comment by forkiesassds** [comment]
Pretty much every extension. This is why I programmatically generate the config without any predefined settings.

**Comment by UnknownShadow200** [comment]
Does e0529d2fc09dc63bce960530be788e028f6785c2 address this?

**Comment by forkiesassds** [comment]
yes.

**Pull request closed without merging**
