### PR TITLE
merge DireDay fork into master

### PR DESCRIPTION
**Pull request by CleverDino**

### CODE REVIEW

**Comment by UnknownShadow200** [comment]
??????

**Comment by UnknownShadow200** [comment]
I'm assuming this was a mistake and closing.

**Comment by CleverDino** [comment]
It wasn't a mistake it's a genuine pull request.

**Comment by Goodlyay** [comment]
https://github.com/Hetal728/MCGalaxy/pull/438/commits/10453667513f76a17cfc23fc0c53da748ca757be

Lol?

**Comment by UnknownShadow200** [comment]
Well, I cannot accept this pull request still for multiple reasons.

```
merge DireDay fork into master 
```
Doesn't tell when looking through pull requests what this actually changed.
```
https://raw.githubusercontent.com/DireDay-the-coder/...
```
Updating shouldn't be using files from your fork.

```
Added stat for Banned
fixed ban stat
Revert "fixed ban stat"
Revert "Added stat for Banned
```
These commits are pointless then and shouldn't be included in the pull request.

```
-        public override void Use(Player p, string message) {
+        public override void Use(Player p, string message)
+        {
```
Why change all the formatting of 240 or so Use() methods, so they are inconsistent with the style of the rest of the code base, for no reason. And with a change reason of "n/a".

```
-    public sealed class CmdMoveAll : Command {
+    public sealed class CmdKickAll : Command {
```
Why was this done, when it still has command name, shortcut, help, and functionality of moving all players.

```
            new TopStat("Recent", PlayerData.DBTable, 
                        PlayerData.ColumnLastLogin,
                        () => "Most recent players", FormatDate),
            new TopStat("Least-Recent", PlayerData.DBTable,
                        PlayerData.ColumnLastLogin,
                        () => "Least Recent players", FormatDate, true),
```
This might be a nice addition.

```
Player.Message(p, "  Idle for {0},last action was at {1}", who.IdleTime.Shorten(), who.LastAction.ToString("dd-MM-yyyy hh:mm tt"));
```
IdleTime is already calculated from now - LastAction, it's unnecessary to include exact date and time of last action here.

```
+ if (who.TotalTimeOnline.Ticks > 0)
+                Player.Message(p, "  %Shas been a player on the server for &a{0} since &a{1}",
+                               who.TotalTime.Shorten(), who.Last.ToString("dd-MM-yyyy hh:mm tt"));
```
TotalTimeOnline is assigned but TotalTime isn't in CmdWhoIs, so this always outputs '0m'.
 I don't understand why Last date joined was used here either.
```
+            else
+                Player.Message(p, "  %Shas been a player on the server for &a{0}", who.TotalTimeOnline.Shorten());
```
Same issue as above. TotalTimeOnline isn't assigned (and the previous if case handles if online ticks > 0 anyways), so this outputs 0m too.

```
-            if (!CommandParser.GetInt(p, limitArg, "Limit", ref limit, 1, 15)) return -1;
+            if (!CommandParser.GetInt(p, limitArg, "Limit", ref limit, 1, 200)) return -1;
```
That's a pretty big change, it should have a proper commit message instead of "readded prev changes".


I apologise if this comes off as overly critical

**Pull request closed without merging**
