### PR TITLE
Add /os map fixgrass

### PR DESCRIPTION
**Pull request by VenkSociety**
Prior to this commit, you had to use /fixgrass to fix grass. But on some servers /fixgrass is restricted to staff-only due to publicly buildable worlds such as freebuilds etc.

### CODE REVIEW

**Comment by Goodlyay** [comment]
You should allow /os fixgrass [args of original command] in addition to just ""

**Comment by VenkSociety** [comment]
Forgot about /fixgrass [mode]. Woops.

**Comment by Goodlyay** [comment]
UseCommand(p, "FixGrass " + value");

This is messed up. You need to pass value in as a second argument, not concatenated onto the command name. And even if you were trying to concatenate this has an extra " at the end.

**Comment by VenkSociety** [comment]
Just change `UseCommand(p, "FixGrass " + value");` to `UseCommand(p, "FixGrass", value);`, it'd be pointless for me to add another commit to the pull for that reason.

**Comment by VenkSociety** [comment]
Closing for now.

**Pull request closed without merging**
