### PR TITLE
Allow checking specific player's ping in /ping

### PR DESCRIPTION
**Pull request by xcta**

### CODE REVIEW

**Comment by Goodlyay** [comment]
What's going on with the indentation and curly bracket placement here?

**Comment by xcta** [comment]
Yeah I'm sorry, Visual Studio likes to do that.

**Comment by UnknownShadow200** [comment]
Use
```CSharp
Player who = PlayerInfo.FindMatches(p, message);
if (who == null) return;
```
instead of `PlayerInfo.FindExact`

**Comment by xcta** [comment]
Done

**Comment by UnknownShadow200** [comment]
Thanks

**Pull request merged**
