### PR TITLE
Make /8ball public chat

### PR DESCRIPTION
**Pull request by PatchTest**

### CODE REVIEW

**Comment by UnknownShadow200** [comment]
Can you make another pull request with just one commit?

**Comment by PatchTest** [comment]
i can try, how do i do that?

**Comment by UnknownShadow200** [comment]
Are you using an actual git client, or are you just editing via the webpage?

**Comment by PatchTest** [comment]
I'm using an actual git client (GitHub for Desktop)

**Comment by UnknownShadow200** [comment]
Very simple and lazy way: Copy Cmd8ball changes somewhere, delete your fork and clone again, then readd the changes.

Other way: Copy Cmd8ball changes somewhere, progressively do "git reset HEAD~" until your repository's last commit is the same as a commit from this one, then do "git pull git@github.com:Hetal728/MCGalaxy.git master". Then readd the changes.

**Comment by 143mailliw** [comment]
fine

**Comment by 143mailliw** [comment]
can you close this, too lazy to login to my other account

**Pull request closed without merging**
