### PR TITLE
Introduced new /BotWhere command prompting current position of bots

### PR DESCRIPTION
**Pull request by johannespartin**

### CODE REVIEW

**Comment by Goodlyay** [comment]
It might be noted that Matcher.FindBots _only_ finds bot that are in the same level as you, which makes the mention of level in the help and output a little bit confusing.

**Comment by johannespartin** [comment]
@Goodlyay thank you for the hint. I've adjusted it accordingly.

**Comment by johannespartin** [comment]
@UnknownShadow200 what do you think about this command?

**Comment by UnknownShadow200** [comment]
1) Shouldn't use `p.FormatNick` here as that only works for player names

2) Personally I think this should be part of `/BotInfo` rather than a separate command

**Pull request closed without merging**
