### PR TITLE
Allow more precise heartbeat configuration

### LINKED ISSUE #636: Multiple user defineable heartbeat adresses.
Might also include prefix or suffix support to allow separation from which server list players joined.

### PR DESCRIPTION
**Pull request by forkiesassds**
Closes #636.

Not sure if you will like certain changes I have done...

### CODE REVIEW

**Comment by UnknownShadow200** [comment]
Unfortunately all those changes relating to ClassiCubeAccountPlus / RemoveLastPlus break backwards compatibility, and I cannot merge changes like that

**Comment by forkiesassds** [comment]
I've reverted some of the changes that have comments mentioning stuff related with backwards compatibility. Let me know if I missed any.

**Comment by forkiesassds** [comment]
Are there still any possible backwards compatibility problems?

**Comment by UnknownShadow200** [comment]
The remaining changes to ClassiCubeAccountPlus related code and removal of RemoveLastPlus() are still breaking changes

I'm also not a huge fan of how the heartbeat parameters list is written to/loaded from disc now, because that has the potential to make things more difficult in the future if I decide to change the default heartbeat parameters

I've thought about an alternative approach, so I'll try to find some time to work on that over this weekend

**Comment by UnknownShadow200** [comment]
What's the use case for being able to override every heartbeat parameter?

**Comment by forkiesassds** [comment]
I made this pull request to solve a problem with overlapping usernames, not to allow overriding of every heartbeat parameter

**Comment by UnknownShadow200** [comment]
What were all the changes to heartbeat to use `"%port"` etc for then?

**Comment by forkiesassds** [comment]
> 
> 
> What were all the changes to heartbeat to use `"%port"` etc for then?

It's so you can reconfigure the heartbeat, `%port` is a placeholder, and it gets replaced with the actual port.

**Comment by UnknownShadow200** [comment]
Right. But my question is more what has reconfiguring the heartbeat got to do with adjusting usernames

**Comment by MisterSheeple** [comment]
Players from Betacraft might have the same username as someone else on ClassiCube, so this could allow user data to get messy. So the idea is that each heartbeat could have a different prefix or suffix to separate user data, if needed. Otherwise, this would cause issues with people being able to impersonate other players.

**Comment by UnknownShadow200** [comment]
I just mean reconfiguring the arguments sent in the heartbeat request / `data.HeartbeatArguments `

**Pull request closed without merging**
