### PR TITLE
Game fixes

### PR DESCRIPTION
**Pull request by RandomStrangers**
Fixes games not generating properties on startup. (Thanks 123DMWM)

### CODE REVIEW

**Comment by Goodlyay** [comment]
There are a lot of changes here that don't seem to be related to the PR, like changing .app and csproj configurations as well as the uploaded binaries

**Comment by RandomStrangers** [comment]
This is because Visual Studio required me to update the framework to 4.8 instead of 4.0, the csproj is it adjusting to the version I have.
However, 4.0 should still work if you retarget it again.

**Comment by Goodlyay** [comment]
Right, but those should be left out of the commits

**Comment by RandomStrangers** [comment]
I can't exactly do that easily without having github ignoring the whole entire project.

**Comment by Goodlyay** [comment]
I'd recommend getting github desktop, it makes it really convenient to pick and choose which changes you're going to include in any given commit, for instance I can uncheck this project change 
image

**Pull request closed without merging**
